modLoader="javafml"
loaderVersion="[31,)" 
[[mods]] 
modId="energytesting"
version="1.0"
displayName="Energy Testing Mod" 
description='''
Yems. TheFreak is a simp!
'''

[[dependencies.energytesting]]
    modId="forge" 
    mandatory=true 
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.energytesting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
